#!/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin

# Check OS version
function checkOS() {
        if [[ -e /etc/debian_version ]]; then
                source /etc/os-release
                OS="${ID}" # debian or ubuntu
        elif [[ -e /etc/centos-release ]]; then
                source /etc/os-release
                OS=centos
	elif [[ -e /etc/rocky-release ]]; then
		source /etc/os-release
		OS=centos
	elif [[ -e /etc/almalinux-release ]]; then
		source /etc/os-release
		OS=centos
        elif [[ -e /etc/vzlinux-release ]]; then
                source /etc/os-release
                OS=centos
        else
                echo "Looks like you aren't running this installer on a Debian, Ubuntu or CentOS system"
                rm -rf /etc/cron.d/cron-cloud-install
                exit 1
        fi
}

# True when a guest NIC already has more than one address (OnApp alias, dual-stack, extra ifcfg).
function guestHasNicWithMultipleIps() {
        if [[ -f /etc/network/interfaces ]] && awk '
                $1 == "iface" && $2 != "lo" {
                        split($2, a, ":")
                        count[a[1]]++
                }
                END {
                        for (d in count)
                                if (count[d] > 1)
                                        exit 0
                        exit 1
                }
        ' /etc/network/interfaces; then
                return 0
        fi
        if compgen -G '/etc/sysconfig/network-scripts/ifcfg-*:*' > /dev/null; then
                return 0
        fi
        if grep -E '^IPADDR[0-9]+=' /etc/sysconfig/network-scripts/ifcfg-* 2>/dev/null | grep -qv '/ifcfg-lo:'; then
                return 0
        fi
        return 1
}

function writeOnappCloudCfg() {
        mkdir -p /etc/cloud/cloud.cfg.d
        if [[ "${DISABLE_CLOUDINIT_NETWORK}" == "yes" ]]; then
                cat << EOF > /etc/cloud/cloud.cfg.d/onapp.cfg
ssh_deletekeys: false
preserve_hostname: true
network:
  config: disabled
EOF
        else
                cat << EOF > /etc/cloud/cloud.cfg.d/onapp.cfg
ssh_deletekeys: false
preserve_hostname: true
EOF
        fi
}

# Single-IP guests: let cloud-init own ENI like before. Multi-IP: keep OnApp interfaces.
function maybeHandOverEniToCloudInit() {
        if [[ "${DISABLE_CLOUDINIT_NETWORK}" == "yes" ]]; then
                return
        fi
        if [[ -f /etc/network/interfaces ]]; then
                cat << EOF > /etc/network/interfaces
source /etc/network/interfaces.d/*
EOF
        fi
}

# Install Cloudinit
function installCloudinit() {
        if guestHasNicWithMultipleIps; then
                DISABLE_CLOUDINIT_NETWORK=yes
                echo "NIC with multiple IPs: disabling cloud-init network config"
        else
                DISABLE_CLOUDINIT_NETWORK=no
        fi
        if [[ ${OS} == 'ubuntu' ]]; then
                apt-get update
                apt-get install -y cloud-init cloud-guest-utils net-tools
                rm -rf /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg
                rm -rf /etc/cloud/cloud.cfg.d/99-installer.cfg
                rm -rf /etc/netplan/00-installer-config.yaml
		writeOnappCloudCfg
		version=$(echo ${VERSION_ID} | cut -d. -f1)
		if [ $version -ge 20 ];
		then
			if dpkg --verify $pkg
			then
				echo "$pkg installed"
				if [[ -f /etc/network/interfaces ]]; then
					cp /etc/network/interfaces /etc/network/onapp2vhi.interfaces
				fi
				maybeHandOverEniToCloudInit
				echo 'datasource_list: [ ConfigDrive, OpenStack, None ]' | sudo -s tee /etc/cloud/cloud.cfg.d/90_dpkg.cfg
				dpkg-reconfigure -f noninteractive cloud-init
				if [[ "${DISABLE_CLOUDINIT_NETWORK}" != "yes" ]]; then
					sed -i "s/'netplan', 'eni'/'eni'/g" /etc/cloud/cloud.cfg
				fi
				cloud-init clean --seed --logs
				cloud-init init --local
				rm -rf /etc/cron.d/cron-cloud-install
			else
				echo "$pkg NOT installed"
				exit 1
			fi
		else
                        if dpkg --verify $pkg
                        then
                                echo "$pkg installed"
				if [[ -f /etc/network/interfaces ]]; then
					cp /etc/network/interfaces /etc/network/onapp2vhi.interfaces
				fi
				maybeHandOverEniToCloudInit
                                echo 'datasource_list: [ ConfigDrive, OpenStack, None ]' | sudo -s tee /etc/cloud/cloud.cfg.d/90_dpkg.cfg
                                dpkg-reconfigure -f noninteractive cloud-init
                                cloud-init clean --seed --logs
                                cloud-init init --local
                                rm -rf /etc/cron.d/cron-cloud-install
                        else
                                echo "$pkg NOT installed"
                                exit 1
			fi
		fi
        elif [[ ${OS} == 'debian' ]]; then
                apt update
                apt-get install -y cloud-init cloud-guest-utils net-tools
                writeOnappCloudCfg
                if dpkg --verify $pkg
                then
                        echo "$pkg installed"
			if [[ -f /etc/network/interfaces ]]; then
				cp /etc/network/interfaces /etc/network/onapp2vhi.interfaces
			fi
			maybeHandOverEniToCloudInit
                        cloud-init clean --seed --logs
                        cloud-init init --local
                        rm -rf /etc/cron.d/cron-cloud-install
                else
                        echo "$pkg NOT installed"
                        exit 1
                fi
        elif [[ ${OS} == 'centos' ]]; then
                yum -y install cloud-init cloud-utils-growpart
                writeOnappCloudCfg
                if rpm -q $pkg
                then
                        echo "$pkg installed"
			if [[ -f /etc/sysconfig/network-scripts/ifcfg-eth0 ]]; then
				cp /etc/sysconfig/network-scripts/ifcfg-eth0 /etc/sysconfig/network-scripts/onapp2vhi.ifcfg-eth0
			fi
                        cloud-init clean --seed --logs
                        cloud-init init --local
                        rm -rf /etc/cron.d/cron-cloud-install
                else
                        echo "$pkg NOT installed"
			exit 1
                fi

        fi

}

if [[ ! "$(dmidecode -s system-manufacturer)" == "Virtuozzo" ]]; then
        echo "system-manufacturer type must be Virtuozzo"
        exit 1
fi

pkg="cloud-init"

checkOS
installCloudinit

systemctl enable cloud-init-local.service 
systemctl enable cloud-init.service
systemctl enable cloud-config.service
systemctl enable cloud-final.service
