#!/bin/bash

if [ ! -f /opt/vz-guest-tools-lin.tar ]; then
    echo "File vz-guest-tools-lin.tar does not exist."
    exit 1
fi


mkdir -p /opt/vz-guest-tools-lin
tar  -xvf /opt/vz-guest-tools-lin.tar -C /opt/vz-guest-tools-lin
bash /opt/vz-guest-tools-lin/install

rm -f /etc/cron.d/cron-vz-guest-tools-install
