#!/usr/bin/env python3
import os
import sys
import click
import warnings
warnings.filterwarnings(action='ignore', module='.*paramiko.*')


plugin_folder = os.path.join(os.path.dirname(__file__), 'ops')


if len(sys.argv) <= 1:
    print("Ask for help with './onapp2vhi --help' command.")
    exit(1)

if str(sys.argv[1]) in ("--help", "help", "man", "--h"):
    okgreen = '\033[92m'
    okcyan = '\033[96m'
    bold = '\033[1m'
    endc = '\033[0m'
    _providers = ('create_service_user', 'list_onapp_users', 'list_onapp_vms', 'migrate')
    _str_prov = ''
    for i, provider in enumerate(_providers):
        if i == 0:
            _str_prov = _str_prov + '   ' + provider + '\n    '
            continue

        _str_prov = _str_prov + provider + '\n    '
    print(f"{bold}{okgreen}Providers:{endc}\n {bold}{okcyan}{_str_prov}{endc}")
    exit(1)


class MyCLI(click.MultiCommand):

    def list_commands(self, ctx):
        rv = []
        for filename in os.listdir(plugin_folder):
            if filename.endswith('.py'):
                rv.append(filename[:-3])
        rv.sort()
        return rv

    def get_command(self, ctx, name):
        ns = {}
        fn = os.path.join(plugin_folder, name + '.py')
        with open(fn) as f:
            code = compile(f.read(), fn, 'exec')
            eval(code, ns, ns)
        return ns['cli']


cli = MyCLI(help='This tool\'s subcommands are loaded from a '
                 'plugin folder dynamically.')

if __name__ == '__main__':
    cli()
