#!/usr/bin/env python2
import os
import platform
import sys
import re
import importlib
import pip
import click
import click_default_group
import colorlog

plugin_folder = os.path.join(os.path.dirname(__file__), 'ops')

os_distro = str(platform.linux_distribution()[0]).split(' ')[0]
os_version = str(platform.linux_distribution()[1]).split('.')[0]

# if os_distro != 'CentOS' or os_version < 7:
#   print "OS: {distro} {version}".format(distro=os_distro,version=os_version)
#   print "Operating system distro should be Centos 7 or higher!"
#   exit(7)


if len(sys.argv) <= 1:
    print("Ask for help with 'onapp2vhi help' command.")
    exit(11)

if str(sys.argv[1]) in ("--help", "help", "man", "--h"):
    _providers = sorted([filename[:-3] for filename in os.listdir(plugin_folder)
                         if filename.endswith('.py') and not filename.startswith('__')])
    _str_prov = ''
    for i, provider in enumerate(_providers):
        if i == 0:
            _str_prov = _str_prov + '   ' + provider + '\n    '
            continue

        _str_prov = _str_prov + provider + '\n    '
    print("Providers:\n {prov}".format(prov=_str_prov))
    exit(1)


class MyCLI(click.MultiCommand):

    def list_commands(self, ctx):
        rv = []
        for filename in os.listdir(plugin_folder):
            if filename.endswith('.py'):
                rv.append(filename[:-3])
        rv.sort()
        return rv

    def get_command(self, ctx, name):
        ns = {}
        fn = os.path.join(plugin_folder, name + '.py')
        with open(fn) as f:
            code = compile(f.read(), fn, 'exec')
            eval(code, ns, ns)
        return ns['cli']


cli = MyCLI(help='This tool\'s subcommands are loaded from a '
                 'plugin folder dynamically.')

if __name__ == '__main__':
    cli()
