# please use symlink for your own settings
# rename this file to config.yaml
# command: ln -s <this config.yaml path> <your config path>
# onapp:
#   host: onapp2vhi.onappdev.com
#   user: your_name
#   port: port_number
#   migration_tool_dir: /your/path/to/onapp2vhi/
#   virtual_env: /your/path/to/venv/bin/activate

# vhi:
#    host: onapp2vhicp.onappdev.com
#    user: root