#!/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin

# Check OS version
function checkOS() {
        if [[ -e /etc/debian_version ]]; then
                source /etc/os-release
                OS="${ID}" # debian or ubuntu
        elif [[ -e /etc/centos-release ]]; then
                source /etc/os-release
                OS=centos
	elif [[ -e /etc/rocky-release ]]; then
		source /etc/os-release
		OS=centos
	elif [[ -e /etc/almalinux-release ]]; then
		source /etc/os-release
		OS=centos
        elif [[ -e /etc/vzlinux-release ]]; then
                source /etc/os-release
                OS=centos
        else
                echo "Looks like you aren't running this installer on a Debian, Ubuntu or CentOS system"
                rm -rf /etc/cron.d/cron-cloud-install
                exit 1
        fi
}

# Install Cloudinit
function installCloudinit() {
        if [[ ${OS} == 'ubuntu' ]]; then
                apt-get update
                apt-get install -y cloud-init cloud-guest-utils net-tools
                rm -rf /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg
                rm -rf /etc/cloud/cloud.cfg.d/99-installer.cfg
                rm -rf /etc/netplan/00-installer-config.yaml
		echo "ssh_deletekeys: false" > /etc/cloud/cloud.cfg.d/onapp.cfg
                echo "preserve_hostname: true"  >> /etc/cloud/cloud.cfg.d/onapp.cfg
                mv /etc/network/interfaces /etc/network/onapp2vhi.interfaces
                cat << EOF > /etc/network/interfaces
source /etc/network/interfaces.d/*
EOF
		version=$(echo ${VERSION_ID} | cut -d. -f1)
		if [ $version -ge 20 ];
		then
			if dpkg -l $pkg
			then
				echo "$pkg installed"
				echo 'datasource_list: [ ConfigDrive, OpenStack, None ]' | sudo -s tee /etc/cloud/cloud.cfg.d/90_dpkg.cfg
				dpkg-reconfigure -f noninteractive cloud-init
				sed -i "s/'netplan', 'eni'/'eni'/g" /etc/cloud/cloud.cfg
				cloud-init clean --seed --logs
				cloud-init init --local
				rm -rf /etc/cron.d/cron-cloud-install
			else
				echo "$pkg NOT installed"
				exit 1
			fi
		else
                        if dpkg -l $pkg
                        then
                                echo "$pkg installed"
                                echo 'datasource_list: [ ConfigDrive, OpenStack, None ]' | sudo -s tee /etc/cloud/cloud.cfg.d/90_dpkg.cfg
                                dpkg-reconfigure -f noninteractive cloud-init
                                cloud-init clean --seed --logs
                                cloud-init init --local
                                rm -rf /etc/cron.d/cron-cloud-install
                        else
                                echo "$pkg NOT installed"
                                exit 1
			fi
		fi
        elif [[ ${OS} == 'debian' ]]; then
                apt update
                apt-get install -y cloud-init cloud-guest-utils net-tools
                echo "ssh_deletekeys: false" > /etc/cloud/cloud.cfg.d/onapp.cfg
                echo "preserve_hostname: true"  >> /etc/cloud/cloud.cfg.d/onapp.cfg
                mv /etc/network/interfaces /etc/network/onapp2vhi.interfaces
                cat << EOF > /etc/network/interfaces
source /etc/network/interfaces.d/*
EOF
                if dpkg -l $pkg
                then
                        echo "$pkg installed"
                        cloud-init clean --seed --logs
                        cloud-init init --local
                        rm -rf /etc/cron.d/cron-cloud-install
                else
                        echo "$pkg NOT installed"
                        exit 1
                fi
        elif [[ ${OS} == 'centos' ]]; then
		mv /etc/sysconfig/network-scripts/ifcfg-eth0 /etc/sysconfig/network-scripts/onapp2vhi.ifcfg-eth0
                yum -y install cloud-init cloud-utils-growpart
                echo "ssh_deletekeys: false" > /etc/cloud/cloud.cfg.d/onapp.cfg
                echo "preserve_hostname: true"  >> /etc/cloud/cloud.cfg.d/onapp.cfg
                if rpm -q $pkg
                then
                        echo "$pkg installed"
                        cloud-init clean --seed --logs
                        cloud-init init --local
                        rm -rf /etc/cron.d/cron-cloud-install
                else
                        echo "$pkg NOT installed"
			exit 1
                fi

        fi

}

if [[ ! "$(dmidecode -s system-manufacturer)" == "Virtuozzo" ]]; then
        echo "system-manufacturer type must be Virtuozzo"
        exit 1
fi

pkg="cloud-init"

checkOS
installCloudinit

systemctl enable cloud-init-local.service 
systemctl enable cloud-init.service
systemctl enable cloud-config.service
systemctl enable cloud-final.service
