#!/bin/bash

function checkNetwork() {
	ping -c5 -q 8.8.8.8

	if [ $? -ne 0 ]; then
		echo -e "\n Please check network configuration"
		exit 1
	fi

	getent ahosts google.com

	if [ $? -ne 0 ]; then
		echo -e "\n Please check DNS configuration"
		exit 1
	fi
}

checkNetwork


if [ ! -f /opt/vz-guest-tools-lin.tar ]; then
    echo "File vz-guest-tools-lin.tar does not exist."
    exit 1
fi


mkdir /opt/vz-guest-tools-lin
tar  -xvf /opt/vz-guest-tools-lin.tar -C /opt/vz-guest-tools-lin
bash /opt/vz-guest-tools-lin/install
